---
- name: MY AS3 PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    uri_method: POST


  vars_files:
    - ../creds/big_creds.yaml


  tasks:
  - name: Create AS3 Declaration
    uri:
      url: https://35.176.27.123/mgmt/shared/appsvcs/declare
      user: "{{ big_user }}"
      password: "{{ big_pass }}"
      method: "{{ uri_method }}"
      body: "{{ lookup('file','as3-declaration2.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no 
...